#! /usr/bin/env python

def options(opt):
    opt.load("gnu_dirs")

def configure(cnf):
    cnf.load("gnu_dirs")

def build(bld):
    bld.load("installdir", tooldir="..")
    bld.install_dir("${SYSCONFDIR}", "empty_dir")
